"""The snapshot as Prometheus text.

Generated by hand rather than with a client library, for the same reason the
rest of this daemon is stdlib: the format is a few lines of string formatting
and the project has no third-party runtime dependency anywhere.

Scraped by the Prometheus on the Pi, which holds 365 days. That is why the page
carries no charts of its own, and why the metric names here are load-bearing --
four alert rules are built on them.
"""

_BUSY = ("working", "waiting_for_slot")


def _escape(value):
    return str(value).replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")


def _metric(out, name, help_text, kind, samples):
    """Emit one metric family. Skipped entirely when it has no samples, so an
    unmeasured rate is absent rather than reported as a misleading zero."""
    if not samples:
        return
    out.append(f"# HELP {name} {help_text}")
    out.append(f"# TYPE {name} {kind}")
    for labels, value in samples:
        label_text = ""
        if labels:
            label_text = "{" + ",".join(
                f'{k}="{_escape(v)}"' for k, v in labels.items()) + "}"
        out.append(f"{name}{label_text} {value}")


def render(snap):
    out = []
    totals = snap["totals"]
    lanes = snap["lanes"]

    _metric(out, "encode_batch_up",
            "1 when an archive-batch process is alive.", "gauge",
            [(None, int(bool(snap["batch"]["running"])))])
    _metric(out, "encode_roster_error",
            "1 when the roster will not parse; every lane parks silently when "
            "this happens, so it is worth an alert.", "gauge",
            [(None, int(bool(snap["roster_error"])))])
    _metric(out, "encode_manifest_error",
            "1 when the manifest will not parse.", "gauge",
            [(None, int(bool(snap.get("manifest_error"))))])
    _metric(out, "encode_clips", "Clips by status.", "gauge",
            [({"status": s}, totals[s]) for s in ("done", "failed", "queued")])

    # Both frames families are omitted when the manifest yielded no clips, and
    # that guard is load-bearing rather than tidy. frames_done is a counter, and
    # model._clips returns no clips when the manifest is missing or will not
    # parse -- so without this, an unreadable manifest drops the counter from
    # 6.1M to 0 and the repair drops it back. Prometheus reads that pair as a
    # reset followed by 6.1M frames of fresh progress, so increase() over the
    # next four hours is nonsense and the EncodeNoProgress alert cannot fire
    # during exactly the window something is wrong. An absent metric says "I do
    # not know"; a zero says "nothing has been done", and only one is true.
    #
    # Guarding on manifest_error is not enough: a missing manifest is
    # deliberately not an error, so an unmounted run directory would zero the
    # counter with no error flag raised anywhere.
    if totals["clips"]:
        _metric(out, "encode_frames",
                "Frames in the manifest.", "gauge", [(None, totals["frames"])])
        _metric(out, "encode_frames_done_total",
                "Frames in clips that finished.", "counter",
                [(None, totals["frames_done"])])

    _metric(out, "encode_lane_enabled",
            "1 when the roster has this lane switched on.", "gauge",
            [({"lane": l["name"]}, int(bool(l["enabled"]))) for l in lanes])
    _metric(out, "encode_lane_busy",
            "1 when this lane holds a clip.", "gauge",
            [({"lane": l["name"]}, int(l["state"] in _BUSY)) for l in lanes])
    _metric(out, "encode_lane_fps_live",
            "Frames a second right now, from the lane's frame counter. Absent "
            "when nothing has been counted yet; zero means measured as zero.",
            "gauge",
            [({"lane": l["name"]}, l["fps_live"])
             for l in lanes if l["fps_live"] is not None])
    _metric(out, "encode_lane_fps",
            "End-to-end frames a second over recent finished clips, staging "
            "and publishing included.", "gauge",
            [({"lane": l["name"]}, l["fps_recent"])
             for l in lanes if l["fps_recent"] is not None])
    _metric(out, "encode_lane_clips_done_total",
            "Clips this lane finished.", "counter",
            [({"lane": l["name"]}, l["clips_done"]) for l in lanes])
    _metric(out, "encode_lane_phase_ratio",
            "Share of a clip's wall time spent in each phase.", "gauge",
            [({"lane": l["name"], "phase": phase}, share)
             for l in lanes if l["phase_split"]
             for phase, share in l["phase_split"].items()])

    return "\n".join(out) + "\n"
